! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert
! #terralith:skylands > null

minecraft:windswept_hills > foolish:storm_jungle
minecraft:birch_forest > foolish:overgrowth
minecraft:old_growth_birch_forest > foolish:sacilite_bloom
minecraft:desert > foolish:sands_of_time
minecraft:badlands > foolish:sands_of_time
minecraft:wooded_badlands > foolish:sands_of_time
minecraft:forest > foolish:scarlet_fields
minecraft:sparse_jungle > fantasy_trees:fantasy_jungle
minecraft:jungle > fantasy_trees:fantasy_jungle
minecraft:dark_forest > fantasy_trees:fantasy_dark_forest
fantasy_trees:fantasy_birch_forest > minecraft:meadow
minecraft:savanna > minecraft:plains
minecraft:savanna_plateau > minecraft:plains
minecraft:windswept_savanna > minecraft:plains
