#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jul 12 12:41:50 AEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=6
shaderPack=ComplementaryUnbound_r5.8.1.zip
