#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jul 11 19:31:45 PDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=Solas Shader V3.6.zip
enableShaders=true
