#This file stores configuration options for Iris, such as the currently active shaderpack
<<<<<<< HEAD
#Sat Jul 11 19:31:45 PDT 2026
=======
#Sun Jul 12 12:41:50 AEST 2026
>>>>>>> be50937ae2cfa145077150a66fcd5ee767fbf527
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=6
shaderPack=ComplementaryUnbound_r5.8.1.zip
